# 服务端口 和 环境
---
server:
  port: 8081
spring:
  profiles: dev
---
server:
  port: 8082
spring:
  profiles: test
---

# 应用名
spring:
  application:
    name: service-vod

  # 开发 测试 正式 环境 设置  dev、test、prod
  profiles:
    active: dev

  # swagger2 配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 配置 上传文件的大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB

  # mysql 数据库 连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/glkt_vod?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource

  # 返回json 的全局 时间 格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 配置 nacos 的 地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#不同的服务器，地址不同； 腾讯云 cos 对象存储，存文件
tencent:
  cos:
    file:
      # cos 桶 的地域
      region: ap-beijing
      # cos 桶的 id  和 key
      secretid: AKIDxqXzCG8qKaorrxwiK4iDW7cxOnFZicJx
      secretkey: c4MqFYozxkN6vd9UfdO1Wq11oSzQkwz5
      # bucket可以在控制台创建，也可以使用java代码创建
      bucketname: webkt-1259440123